# Base image
FROM node:14-alpine

# Set working directory
WORKDIR /app/Frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Serve the application
CMD ["npm", "start"]
