version: '3.8'

services:
  react-app: my-react-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  api:
    image: my-react-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
